# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings


exclude: ["README.md"] # files to exclude
gems: [jekyll-paginate]
paginate: 5 # pagination based on number of posts
paginate_path: "page:num"
highlighter: rouge
markdown: kramdown
comments: true


defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: muzir Web NotlarÄ±

description: Stylish Jekyll Theme
author:
  name: muzir
  email: baycelik_erhun@hotmail.com
  github: muzir
  twitter: erhunbaycelik
  stackoverflow: 1577363
  linkedin: erhunbaycelik/
  bio: Waiting is painful. Forgetting is painful. But not knowing which to do is the worse kind of suffering. Paulo Coelho	
  email_md5: ae62fee595816cf8bf939fb4ddba6a98
rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html

BASE_PATH:
