# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude

title: dbyll
author:
  name: dbyll
  email: dbyll@ismaildemirbilek.com
  github: dbtek
  twitter: asd123
  pinterest: asd123
  linkedin: asd123
  resume: asd123
  bio: Your stylish, minimalist theme!
  email_md5: 726351295ec82e145928582f595aa3aa
  
BASE_PATH: /

categories_path: categories.html
tags_path: tags.html
